# Generated by Django 5.2 on 2026-04-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='ue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
