# Generated by Django 5.2 on 2026-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('EXPORT', 'Export'), ('PUBLISH', 'Publication'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('ERROR', 'Erreur'), ('WARNING', 'Avertissement')], max_length=20)),
                ('module', models.CharField(choices=[('AUTH', 'Authentification'), ('USERS', 'Utilisateurs'), ('MAQUETTE', 'Maquette'), ('ROOMS', 'Salles'), ('TIMETABLE', 'Emploi du temps'), ('SETTINGS', 'Paramètres'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=10)),
                ('user_display', models.CharField(blank=True, default='Système', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('target', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée journal',
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['module'], name='audit_audit_module_e8d32b_idx'), models.Index(fields=['severity'], name='audit_audit_severit_f33e16_idx')],
            },
        ),
    ]
